"""empty message

Revision ID: 6c0dfcb86623
Revises: 2faf6ce5edd7
Create Date: 2018-12-06 18:50:05.663844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0dfcb86623'
down_revision = '2faf6ce5edd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('ad_id', sa.INTEGER(), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
