"""empty message

Revision ID: b8dca3ad8ea6
Revises: 58584346ff01
Create Date: 2018-12-12 17:40:27.867725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8dca3ad8ea6'
down_revision = '58584346ff01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'ad', ['ad_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'ad', ['ad_id'], ['id'])
    # ### end Alembic commands ###
